apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-crud
  name: bcpa-location-controller
  namespace: ns-location-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-crud
  template:
    metadata:
      labels:
        app: location-crud
    spec:
      containers:
        - image: downeys/bcpa-location-crud
          name: location-crud
          ports:
            - name: location-crud
              containerPort: 8080
---
#Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: location-crud
  name: location-crud
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: location-crud