apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: locationCRUD
  name: bcpa-location-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: locationCRUD
    spec:
      containers:
        - image: downeys/bcpa-location-crud
          name: locationCRUD
          ports:
            - name: locationCRUD
              containerPort: 8080
---
#Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: locationCRUD
  name: locationCRUD
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: locationCRUD