spring:
  application:
    name: downeys-location-crud
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
server:
  port: 8080
keycloak:
  auth-server-url: http://3.21.236.40:8080/auth/
  realm: Master
  resource: bench-login
  public-client: true

