spring:
  application:
    name: downeys-location-crud
  jpa:
    defer-datasource-initialization: true
server:
  port: 8080
keycloak:
  auth-server-url: http://3.21.236.40:8080/auth/
  realm: Master
  resource: bench-login
  public-client: true

